insert into Commercialization (nomeProduto, nomeRegiao, nomeUF, mesEmissao, anoEmissao, cdPrograma, cdSubPrograma, cdFonteRecurso, cdTipoSeguro, qtdCusteio, vlCusteio, atividade, cdModalidade, areaCusteio)
values ("MILHO", "NORDESTE", "CE", "11", "2016", "0999","0","0210", "3",2,3048070.00,"1","30",null);

insert into Commercialization (nomeProduto, nomeRegiao, nomeUF, mesEmissao, anoEmissao, cdPrograma, cdSubPrograma, cdFonteRecurso, cdTipoSeguro, qtdCusteio, vlCusteio, atividade, cdModalidade, areaCusteio)
values ("UVA", "SUL", "RS", "11", "2016", "0999","0","0210", "3",2,3048070.00,"1","30",null);

insert into Commercialization (nomeProduto, nomeRegiao, nomeUF, mesEmissao, anoEmissao, cdPrograma, cdSubPrograma, cdFonteRecurso, cdTipoSeguro, qtdCusteio, vlCusteio, atividade, cdModalidade, areaCusteio)
values ("LEITE", "SUDESTE", "SP", "12", "2016", "0999","0","0210", "3",2,3048070.00,"1","30",null);

insert into Commercialization (nomeProduto, nomeRegiao, nomeUF, mesEmissao, anoEmissao, cdPrograma, cdSubPrograma, cdFonteRecurso, cdTipoSeguro, qtdCusteio, vlCusteio, atividade, cdModalidade, areaCusteio)
values ("FEIJAO", "NORDESTE", "CE", "08", "2020", "0999","0","0210", "3",2,3048070.00,"1","30",null);

insert into Commercialization (nomeProduto, nomeRegiao, nomeUF, mesEmissao, anoEmissao, cdPrograma, cdSubPrograma, cdFonteRecurso, cdTipoSeguro, qtdCusteio, vlCusteio, atividade, cdModalidade, areaCusteio)
values ("TRIGO", "SUDESTE", "SP", "11", "2016", "0999","0","0210", "3",2,3048070.00,"1","30",null);

insert into Commercialization (nomeProduto, nomeRegiao, nomeUF, mesEmissao, anoEmissao, cdPrograma, cdSubPrograma, cdFonteRecurso, cdTipoSeguro, qtdCusteio, vlCusteio, atividade, cdModalidade, areaCusteio)
values ("SOJA", "NORTE", "AM", "04", "2020", "0999","0","0210", "3",2,3048070.00,"1","30",null);

insert into Commercialization (nomeProduto, nomeRegiao, nomeUF, mesEmissao, anoEmissao, cdPrograma, cdSubPrograma, cdFonteRecurso, cdTipoSeguro, qtdCusteio, vlCusteio, atividade, cdModalidade, areaCusteio)
values ("AZEITONA", "NORDESTE", "CE", "4", "2016", "0999","0","0210", "3",2,3048070.00,"1","30",null);

insert into Commercialization (nomeProduto, nomeRegiao, nomeUF, mesEmissao, anoEmissao, cdPrograma, cdSubPrograma, cdFonteRecurso, cdTipoSeguro, qtdCusteio, vlCusteio, atividade, cdModalidade, areaCusteio)
values ("CEVADA", "NORTE", "AM", "2", "2020", "0999","0","0210", "3",2,3048070.00,"1","30",null);

insert into Commercialization (nomeProduto, nomeRegiao, nomeUF, mesEmissao, anoEmissao, cdPrograma, cdSubPrograma, cdFonteRecurso, cdTipoSeguro, qtdCusteio, vlCusteio, atividade, cdModalidade, areaCusteio)
values ("CAFE", "SUL", "PR", "08", "2016", "0999","0","0210", "3",2,3048070.00,"1","30",null);

insert into Commercialization (nomeProduto, nomeRegiao, nomeUF, mesEmissao, anoEmissao, cdPrograma, cdSubPrograma, cdFonteRecurso, cdTipoSeguro, qtdCusteio, vlCusteio, atividade, cdModalidade, areaCusteio)
values ("LARANJA", "SUL", "PR", "09", "2016", "0999","0","0210", "3",2,3048070.00,"1","30",null);